spring:
  datasource: {
    driverClassName: org.h2.Driver,
    url: 'jdbc:h2:file:./h2db/db/soas;DB_CLOSE_DELAY=-1;CACHE_SIZE=131072;LOG=0',
    username: soas,
    password: soas
  }
  jpa:
    properties:
      hibernate: {
        dialect: org.hibernate.dialect.H2Dialect
      }
    hibernate: {
      ddl-auto: update
    }
  h2:
    console:
      enabled: true
      path: /console
      settings: {
        web-allow-others: true
      }
server: {
  port: 9090
}